:zap: Replace Cobertura with Jacoco Gradle plugin
The gradle-cobertura-plugin fails with NoClassDefFoundError
(https://github.com/stevesaliman/gradle-cobertura-plugin/issues/107),
so I've switched to the built-in Jacoco plugin, which works without
a problem.